(TeX-add-style-hook "packages"
 (lambda ()
    (TeX-run-style-hooks
     "menukeys"
     "hyperref"
     "todo"
     "hide"
     "biblatex"
     "backend=biber"
     "enumitem"
     "inline"
     "algssa"
     "algpseudocode"
     "algorithm"
     "dirtree"
     "pifont"
     "smcm-cosc-graphs"
     "smcm-math"
     "array"
     "booktabs"
     "verbatim"
     "listings"
     "csquotes"
     "smcm-common"
     "")))

