(TeX-add-style-hook "refs"
 (lambda ()
    (LaTeX-add-bibitems
     "atallah2009algorithms"
     "chen:spanning-trees"
     "dew:sem"
     "goddard:ssa--k-distance"
     "gairing:distance-2"
     "hagberg:networkx"
     "qadeer:verifying-ssa"
     "python3:ref"
     "yaml:ref"
     "arora:closure-and-convergence"
     "brooks:mythical-man-month"
     "lafon:balanceMQ"
     "dolev:talk"
     "knuth:lit-prog"
     "palesz:graphsharp"
     "tcltk"
     "tkinter"
     "pygame"
     "stackless"
     "gephi"
     "gexf"
     "pygexf"
     "noweb"
     "nose"
     "pyyaml"
     "ssa:dist"
     "gh:libcircle"
     "gh:balancemq"
     "lamport"
     "ex:mobile1"
     "ex:mobile2"
     "ex:mobile3")))

