(TeX-add-style-hook "smp"
 (lambda ()
    (LaTeX-add-bibliographies
     "refs")
    (TeX-add-symbols
     '("meta" 1))
    (TeX-run-style-hooks
     "menukeys"
     "gitinfo"
     "hyperref"
     "hidelinks"
     "tikz"
     "biblatex"
     "backend=biber"
     "fontspec"
     "microtype"
     "todo"
     "marginpar"
     "array"
     "booktabs"
     "fancyhdr"
     "listings"
     "verbatim"
     "csquotes"
     "markup"
     "smcm-cosc-graphs"
     "smcm-math"
     "pifont"
     "amsthm"
     "amssymb"
     "amsmath"
     "latex2e"
     "smcm-cosc-smp12"
     "smcm-cosc-smp"
     ""
     "12pt"
     "letterpaper"
     "maxp=30"
     "minp=25"
     "abstract"
     "sections/introduction"
     "sections/mathematical-representation"
     "sections/logical-representation"
     "sections/interface-ssa"
     "sections/interface-test"
     "sections/interface-interop"
     "sections/reflection")))

